//
// Generated file, do not edit! Created by nedtool 5.7 from Messaging/ProbeVehicleData.msg.
//

#ifndef __VEINS_PROBEVEHICLEDATA_M_H
#define __VEINS_PROBEVEHICLEDATA_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0507
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif

// cplusplus {{
#include "veins/base/utils/Coord.h"
#include "veins/modules/messages/BaseFrame1609_4_m.h"
#include "veins/base/utils/SimpleAddress.h"
// }}


namespace veins {

/**
 * Class generated from <tt>Messaging/ProbeVehicleData.msg:28</tt> by nedtool.
 * <pre>
 * packet ProbeVehicleData extends BaseFrame1609_4
 * {
 *     Coord senderPos;
 *     Coord senderSpeed;
 *     string vehicleTypeID;
 * }
 * </pre>
 */
class ProbeVehicleData : public ::veins::BaseFrame1609_4
{
  protected:
    Coord senderPos;
    Coord senderSpeed;
    ::omnetpp::opp_string vehicleTypeID;

  private:
    void copy(const ProbeVehicleData& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const ProbeVehicleData&);

  public:
    ProbeVehicleData(const char *name=nullptr, short kind=0);
    ProbeVehicleData(const ProbeVehicleData& other);
    virtual ~ProbeVehicleData();
    ProbeVehicleData& operator=(const ProbeVehicleData& other);
    virtual ProbeVehicleData *dup() const override {return new ProbeVehicleData(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual Coord& getSenderPos();
    virtual const Coord& getSenderPos() const {return const_cast<ProbeVehicleData*>(this)->getSenderPos();}
    virtual void setSenderPos(const Coord& senderPos);
    virtual Coord& getSenderSpeed();
    virtual const Coord& getSenderSpeed() const {return const_cast<ProbeVehicleData*>(this)->getSenderSpeed();}
    virtual void setSenderSpeed(const Coord& senderSpeed);
    virtual const char * getVehicleTypeID() const;
    virtual void setVehicleTypeID(const char * vehicleTypeID);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const ProbeVehicleData& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, ProbeVehicleData& obj) {obj.parsimUnpack(b);}

} // namespace veins

#endif // ifndef __VEINS_PROBEVEHICLEDATA_M_H

